In [2]:
import time
import numpy as np
#projet de naomi et prosper :)


#On considère la suite (un)n2N définie par les conditions :
      #u0 = 42 et pour tout n > 1; un = (16383 × un-1) mod 59047
      #J'ai utilisé une liste pour u(n) parce que 
      # ça prend moins de temps pour l'exécution
      
u_all = [42]
a = 42
for i in range(1,10000):
    b = (16383 * a) % 59047
    a = b
    u_all.append(a)

def u(n):
    return u_all[n]

#Question 1: Que valent u996 et u9996 ?
print(u(996))
# u996 = 58034 u9996 = 8178
print(u(9996))
#u9996 = 8178
print(u(1))
#On définit vi = 1 si ui ≡ 0 mod 3 et vi = 0 sinon. Combien y a-t-il d’indices i tels que vi = 0,
                   #pour 0 <= i < 10000 ?

def v(n):
    m = 0
    for i in range(n+1):
        if u(i) % 3 == 0:
            m = 1
        else:
            m = 0
    return m
print(v(0))
#On définit la fonction qui permettra de compter le nombre d'indices
def nb_indice(n):
    current = 0
    for i in range(0,n+1):
        if v(i) == 0:
            current += 1
    return current
#cette petite écriture ne bas permet de voir le temps que met
#la fonction nb_indice pour calculer nb_indice(9999)
start_time = time.time()
print("the program has started")
print(nb_indice(9999))
print("the program took {}".format(time.time() - start_time))

#Rédiger une fonction genere_univers(k) qui prend en argument un entier k et qui renvoie un tableau
#numpy de taille k × k représentant l’univers à l’instant t = 0.
#À la date t = 0, combien l’univers possède-t-il de cellules vivantes pour k = 20 ? et pour k = 50 ?


58034
8178
38569
1
the program has started
6693
the program took 7.45415186882019
[]
[]
[]
[]
[]
[[0.]]
[[0. 0.]]
[[0. 0. 0.]]
[]
[[0.]
 [0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[]
[[0.]
 [0.]
 [0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
import numpy as np
def genere_univers(k):
    for i in range(k):
        for j in range(k):
            a = np.zeros((i,j))
            print("i: ", i, ";j: ", j, "; a:", a, "\n")
            # a[i,j] = 1
            # print(a[i])
            # if v(i+(j*k)) == 1:
                # a[i,j] = 1
    return a

print(genere_univers(4))

i:  0 ;j:  0 ; a: [] 

i:  0 ;j:  1 ; a: [] 

i:  0 ;j:  2 ; a: [] 

i:  0 ;j:  3 ; a: [] 

i:  1 ;j:  0 ; a: [] 

i:  1 ;j:  1 ; a: [[0.]] 

i:  1 ;j:  2 ; a: [[0. 0.]] 

i:  1 ;j:  3 ; a: [[0. 0. 0.]] 

i:  2 ;j:  0 ; a: [] 

i:  2 ;j:  1 ; a: [[0.]
 [0.]] 

i:  2 ;j:  2 ; a: [[0. 0.]
 [0. 0.]] 

i:  2 ;j:  3 ; a: [[0. 0. 0.]
 [0. 0. 0.]] 

i:  3 ;j:  0 ; a: [] 

i:  3 ;j:  1 ; a: [[0.]
 [0.]
 [0.]] 

i:  3 ;j:  2 ; a: [[0. 0.]
 [0. 0.]
 [0. 0.]] 

i:  3 ;j:  3 ; a: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
